import {
  DYNAMICS_SYSTEM_SCHEMA_VERSION,
  type DynamicsTemplate,
} from "../DynamicsSchema";

export const SIMPLE_FOOD_STOCK_TEMPLATE: DynamicsTemplate = {
  id: "simple-food-stock",
  name: "Simple Food Stock",
  description:
    "Layer 1 stock-flow template: food stock changes by production minus demand and is clamped by capacity.",
  system: {
    version: DYNAMICS_SYSTEM_SCHEMA_VERSION,
    id: "simple-food-stock",
    name: "Simple Food Stock",
    description:
      "A minimal food stock model built from generic dynamics nodes.",
    nodes: [
      {
        id: "tilesOwned",
        type: "input",
        name: "tilesOwned",
        position: { x: 0, y: 0 },
        config: { value: 10, min: 0, max: 1000, step: 1, unit: "tiles" },
      },
      {
        id: "population",
        type: "input",
        name: "population",
        position: { x: 0, y: 160 },
        config: { value: 10, min: 0, max: 1000, step: 1, unit: "people" },
      },
      {
        id: "yieldPerTile",
        type: "parameter",
        name: "yieldPerTile",
        position: { x: 0, y: 80 },
        config: { value: 2, min: 0, max: 20, step: 0.1, unit: "food/tile" },
      },
      {
        id: "foodPerPopulation",
        type: "parameter",
        name: "foodPerPopulation",
        position: { x: 0, y: 240 },
        config: {
          value: 1,
          min: 0,
          max: 10,
          step: 0.1,
          unit: "food/person",
        },
      },
      {
        id: "foodStockCapacity",
        type: "parameter",
        name: "foodStockCapacity",
        position: { x: 480, y: 280 },
        config: {
          value: 20_000,
          min: 0,
          max: 100_000,
          step: 100,
          unit: "food",
        },
      },
      {
        id: "foodProduction",
        type: "math",
        name: "foodProduction",
        position: { x: 240, y: 40 },
        config: { operation: "multiply" },
      },
      {
        id: "foodDemand",
        type: "math",
        name: "foodDemand",
        position: { x: 240, y: 200 },
        config: { operation: "multiply" },
      },
      {
        id: "foodProductionFlow",
        type: "flow",
        name: "foodProductionFlow",
        position: { x: 480, y: 40 },
        config: { direction: "inflow", unit: "food/tick" },
      },
      {
        id: "foodDemandFlow",
        type: "flow",
        name: "foodDemandFlow",
        position: { x: 480, y: 200 },
        config: { direction: "outflow", unit: "food/tick" },
      },
      {
        id: "foodStock",
        type: "stock",
        name: "foodStock",
        position: { x: 720, y: 120 },
        config: { initialValue: 0, min: 0, unit: "food" },
      },
      {
        id: "foodStockDelta",
        type: "probe",
        name: "foodStockDelta",
        position: { x: 960, y: 80 },
        config: { charted: true, unit: "food" },
      },
      {
        id: "foodStockOverflow",
        type: "probe",
        name: "foodStockOverflow",
        position: { x: 960, y: 180 },
        config: { charted: true, unit: "food" },
      },
    ],
    edges: [
      {
        id: "tiles-owned-to-production",
        source: "tilesOwned",
        sourceHandle: "value",
        target: "foodProduction",
        targetHandle: "a",
      },
      {
        id: "yield-to-production",
        source: "yieldPerTile",
        sourceHandle: "value",
        target: "foodProduction",
        targetHandle: "b",
      },
      {
        id: "population-to-demand",
        source: "population",
        sourceHandle: "value",
        target: "foodDemand",
        targetHandle: "a",
      },
      {
        id: "food-per-population-to-demand",
        source: "foodPerPopulation",
        sourceHandle: "value",
        target: "foodDemand",
        targetHandle: "b",
      },
      {
        id: "production-to-production-flow",
        source: "foodProduction",
        sourceHandle: "value",
        target: "foodProductionFlow",
        targetHandle: "amount",
      },
      {
        id: "demand-to-demand-flow",
        source: "foodDemand",
        sourceHandle: "value",
        target: "foodDemandFlow",
        targetHandle: "amount",
      },
      {
        id: "production-flow-to-stock",
        source: "foodProductionFlow",
        sourceHandle: "amount",
        target: "foodStock",
        targetHandle: "inflow",
      },
      {
        id: "demand-flow-to-stock",
        source: "foodDemandFlow",
        sourceHandle: "amount",
        target: "foodStock",
        targetHandle: "outflow",
      },
      {
        id: "capacity-to-stock",
        source: "foodStockCapacity",
        sourceHandle: "value",
        target: "foodStock",
        targetHandle: "max",
      },
      {
        id: "stock-to-delta-probe",
        source: "foodStock",
        sourceHandle: "delta",
        target: "foodStockDelta",
        targetHandle: "value",
      },
      {
        id: "stock-to-overflow-probe",
        source: "foodStock",
        sourceHandle: "overflow",
        target: "foodStockOverflow",
        targetHandle: "value",
      },
    ],
  },
  scenario: {
    version: DYNAMICS_SYSTEM_SCHEMA_VERSION,
    id: "simple-food-stock-baseline",
    systemId: "simple-food-stock",
    name: "Baseline",
    tickCount: 60,
    inputValues: {
      tilesOwned: 10,
      population: 10,
    },
    parameterValues: {
      yieldPerTile: 2,
      foodPerPopulation: 1,
      foodStockCapacity: 20_000,
    },
    stockInitialValues: {
      foodStock: 0,
    },
  },
};
